blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings      
from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('blog_app.urls')),
   path('', include('user_app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'
urlpatterns = [
   path('', views.index, name='index'),
   path('detail/<int:post_id>/', views.detail, name='detail'), 
   path('add/', views.add, name='add'), 
   path('edit/<int:post_id>/', views.edit, name='edit'),
   path('delete/<int:post_id>/', views.delete, name='delete'), 
]

user_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user_app'
urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='user_app/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
  path('user/<int:user_id>/', views.detail, name='detail'),
  path('user/edit/<int:user_id>/', views.edit, name='edit'), 
  path('user/delete/<int:user_id>/', views.delete, name='delete')
]

blog_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
 #追加
class Tag(models.Model):
 tag = models.CharField('タグ名', max_length=50)
 def __str__(self):
   return self.tag

class Post(models.Model):
   title = models.CharField('タイトル', max_length=50)
   text = models.TextField('本文')
   image = models.ImageField('画像', upload_to = 'images', blank=True)
   created_at = models.DateTimeField('投稿日', default=timezone.now)
   tag = models.ForeignKey(Tag, verbose_name = 'タグ', on_delete=models.PROTECT) #追加
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   def __str__(self):
       return self.title

user_app/models.py
from django.db import models

# Create your models here.

blog_app/forms.py
from django import forms
from .models import Post, Tag
from django.forms import ModelForm

class PostAddForm(forms.ModelForm):    
   class Meta:
       model = Post
       fields = ['title', 'text', 'image', 'tag']

user_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
  class Meta:
      model = User
      fields = ('username', 'email', 'password1', 'password2')

blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Tag 
from .forms import PostAddForm 
from django.contrib.auth.decorators import login_required


# トップページの関数
def index(request):
   posts = Post.objects.all().order_by('-created_at') 
   return render(request, 'blog_app/index.html', {'posts': posts}) 

#詳細ページの関数
def detail(request, post_id):
     post = get_object_or_404(Post, id=post_id)
     return render(request, 'blog_app/detail.html', {'post': post})

# 投稿用の関数
@login_required
def add(request):
   if request.method == "POST":
      form = PostAddForm(request.POST, request.FILES)
      if form.is_valid():
         post = form.save(commit=False)
         post.user = request.user
         post.save()
         return redirect('blog_app:index')
   else:   
       form = PostAddForm()
   return render(request, 'blog_app/add.html', {'form': form})

# 編集用の関数
@login_required
def edit(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   if request.method == "POST":
       form = PostAddForm(request.POST, request.FILES, instance=post)
       if form.is_valid():
           form.save()
           return redirect('blog_app:detail', post_id=post.id)
   else:
       form = PostAddForm(instance=post)
   return render(request, 'blog_app/edit.html', {'form': form, 'post':post })

@login_required
def delete(request, post_id):
   post = get_object_or_404(Post, id=post_id)
   post.delete()
   return redirect('blog_app:index')

user_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from blog_app .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
  signup_form = SignUpForm(request.POST or None)
  if request.method == "POST" and signup_form.is_valid():
      user = signup_form.save()
      input_username = signup_form.cleaned_data['username']
      input_email = signup_form.cleaned_data['email']
      input_password = signup_form.cleaned_data['password1']
      user = authenticate(username=input_username, email=input_email, password=input_password)
      login(request, user)
      return redirect('blog_app:index')
  context = {
      "signup_form": signup_form,
  }
  return render(request, 'user_app/signup.html', context)
  
def detail(request, user_id):
   user = get_object_or_404(User, id=user_id)
   posts = user.post_set.all().order_by('-created_at')
   return render(request, 'user_app/detail.html', {'user': user, 'posts': posts})

@login_required
def edit(request, user_id):
   user = get_object_or_404(User, id=user_id)
   if request.method == "POST":
       form = SignUpForm(request.POST, instance=request.user)
       if form.is_valid():
           form.save()
           return redirect('user_app:detail', user_id=user.id)
   else:
       form = SignUpForm(instance=user)
   return render(request, 'user_app/edit.html', {'form': form, 'user':user })

@login_required
def delete(request, user_id):
   user = get_object_or_404(User, id=user_id)
   user.delete()
   return redirect('blog_app:index') 

templates/base.html
{% bootstrap_css %} 
{% bootstrap_javascript jquery='full' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
 <head>
   <meta charset="UTF-8">
   <meta name="description" content=""/>
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <title>Blog</title>
 </head>
 <body>
  {% include 'header.html' %}
  <div class="container">
    {% block content %} 
    {% endblock %}
    {% include 'footer.html' %}
 </body>
</html>

templates/blog_app/add.html
{% extends 'base.html' %}
{% load widget_tweaks %} <!-- 追加 -->
{% block content %}
<h1 class="mt-5 pt-4 text-center">新規投稿</h1>
<form action="{% url 'blog_app:add' %}" method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 <label for="id_title" class="sr-only">タイトル</label>
 <input type="text" name="title" placeholder="タイトル" maxlength="50" class="form-control mb-3" required id="id_title">

 <label for="id_text" class="sr-only">本文</label>
 <textarea type="text" name="text" placeholder="本文" cols="40" rows="10" class="form-control mb-3" required id="id_text"></textarea>

 <div class="mb-3 form-control text-secondary">
   <label>画像</label>
       {{ form.image }}
   </div>
     
 <div class="mb-3">
   <label for="id_tag" class="sr-only">タグ</label>
   {{ form.tag|add_class:"custom-select" }}
 </div>

 <button type="submit" class="btn btn-block btn-outline-success">投稿する</button>
</form>
{% endblock %}

templates/blog_app/detail.html
{% extends 'base.html' %}
{% block content %}   
<h1 class="text-center my-5">{{ user.username }}のページ</h1>

<div class="text-center"><a href="{% url 'user_app:edit' user_id=user.id %}"><button type="button" class="btn btn-outline-info">{{user}} 編集</button></a></div>
<div class="card text-secondary" style="margin-top: 55px;">
  {% if post.image %}
  <img style="width: 100%; max-height: 500;" class="img-fluid mx-auto" src="{{ post.image.url }}">
  {% else %}
  <div class="p-1 border border-secondary text-center pt-5" style="min-width: 500; min-height: 400;">No Image</div>
  {% endif %}  <div class="card-body">
    <h3 class="card-title font-weight-bold text-center">{{ post.title }}</h3>
    <div class="p-3">
    <p class="card-text">{{ post.text }}</p>
    <p>#{{post.tag}}</p>
    <p>{{post.created_at}}</p>
    {% if request.user == post.user %}
   <a href="{% url 'blog_app:edit' post_id=post.id %}"><button type="button" class="btn btn-outline-primary">編集</button></a>
   <a href="{% url 'blog_app:delete' post_id=post.id %}"><button type="button" class="btn btn-outline-danger">削除</button></a>
   {% endif %}
  </div>
 </div>
 </div>
{% endblock %}

templates/blog_app/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">編集</h1>
<form method="POST" enctype="multipart/form-data">
 {% csrf_token %}

 <label for="id_title" class="sr-only">タイトル</label>
 {{ form.title|add_class:"form-control mb-3"}}
 <label for="id_text" class="sr-only">本文</label>
 {{ form.text|add_class:"form-control mb-3"}}

 <div class="mb-3 form-control text-secondary">
   <label>画像</label>
       {{ form.image }}
   </div>

 <div class="my-5">
   <label for="id_tag" class="sr-only">タグ</label>
   {{ form.tag|add_class:"custom-select" }}
 </div>

 <button type="submit" class="btn btn-block btn-outline-success">編集する</button>
</form>

{% endblock %}

templates/blog_app/index.html
{% extends 'base.html' %}
{% block content %}   
<h1 class="mt-5 pt-4 text-center">ブログサイト</h1>

<div class="d-flex justify-content-center flex-wrap">
{% for post in posts%}
<a href="{% url 'blog_app:detail' post_id=post.id %}">
 <div class="card m-4" style="min-width: 300; max-height: 490;">
   {% if post.image %}
   <img style="max-width: 300; max-height: 300;" class="card-img-top" src="{{ post.image.url }}">
   {% else %}
   <div class="p-1 border border-secondary text-center pt-5" style="min-width: 300; min-height: 225;">No Image</div>
   {% endif %}
   <div class="card-body">
     <h4 class="card-title">{{post.title|truncatechars:10 | linebreaksbr}}</h4>
     <p class="card-text">
       {{ post.text|truncatechars:17 }}
     </p>
   </a>
   <p></p>
     <p>#{{post.tag}}</p>
     <p>{{post.created_at}} |
     <a href="{% url 'user_app:detail' post.user.id %}">{{post.user.username}}</a></p>
 </div>
</div>
{% endfor %}
</div>
{% endblock %}

templates/footer.html
<footer>
 <h4 class="text-center">CopyRight/2020</h4>
</footer>

templates/header.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'blog_app:index' %}">ブログサイト</a>
 
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
 　　　　{% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_app:detail' request.user.id %}">{{request.user.username}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog_app:add' %}">投稿</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_app:logout' %}">ログアウト</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_app:signup' %}">新規登録</a>
      </li>
 
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_app:login' %}">ログイン</a>
      </li>
      {% endif %}
    </ul>
  </div>
 </nav>

templates/user_app/detail.html
{% extends 'base.html' %}
{% block content %}   
<h1 class="text-center my-5">{{ user.username }}のページ</h1>

{% if request.user == user %}
 <div class="text-center"><a href="{% url 'user_app:edit' user_id=user.id %}"><button type="button" class="btn btn-outline-info">{{user}} 編集</button></a></div>
{% endif %}
<div class="d-flex justify-content-center flex-wrap">
 {% for post in posts%}
 <a href="{% url 'blog_app:detail' post_id=post.id %}">
   <div class="card m-4" style="min-width: 300; max-height: 490;">
     {% if post.image %}
     <img style="max-width: 300; max-height: 300;" class="card-img-top" src="{{ post.image.url }}">
     {% else %}
     <div class="p-1 border border-secondary text-center pt-5" style="min-width: 300; min-height: 225;">No Image</div>
     {% endif %}
     <div class="card-body">
       <h4 class="card-title">{{post.title|truncatechars:10 | linebreaksbr}}</h4>
       <p class="card-text">
         {{ post.text|truncatechars:17 }}
       </p>
     </a>
       <p>#{{post.tag}}</p>
       <p>{{post.created_at}}</p>       
   </div>
 </div>
 {% endfor %}
 </div>
{% endblock %}

templates/user_app/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">{{user.username}}を編集</h1>
 <form class="form-signin" method="post">
   {% csrf_token %}

   <label for="id_username" class="text-secondary">名前</label>
   {{ form.username|add_class:"form-control mb-3" }}

   <label for="id_email" class="text-secondary">メールアドレス</label>
   {{ form.email|add_class:"form-control mb-3"}}

   <label for="id_password1" class="text-secondary">新しいパスワード</label>
   {{ form.password1|add_class:"form-control mb-3"}}

   <label for="id_password2" class="text-secondary">パスワード(確認用)</label>
   {{ form.password2|add_class:"form-control mb-3"}}

   <button type="submit" class="btn btn-block btn-outline-success">編集</button>
 </form>
 {% if request.user == user %}
 <a href="{% url 'user_app:delete' user_id=user.id %}"><button type="button" class="btn btn-outline-danger">退会する</button></a>
{% endif %}
</a>
</div>
</div>
{% endblock %}

templates/user_app/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Login</h1>
<form method="post">
{% csrf_token %}
<label for="id_username" class="sr-only">ユーザー名</label>
<input type="text" name="username" placeholder="ユーザー名" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="form-control mb-3" required id="id_username">

<label for="id_password" class="sr-only">パスワード</label>
<input type="password" name="password" autocomplete="current-password" placeholder="パスワード" class="form-control mb-3" required id="id_password">

<button type="submit" class="btn btn-block btn-outline-success">Login</button>
</form>
{% endblock %}

templates/user_app/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Signup</h1>
 <form class="form-signin" method="post">
   {% csrf_token %}
   <label for="id_username" class="sr-only">タイトル</label>
   <input type="text" name="username" placeholder="名前" maxlength="150" class="form-control mb-3" required id="id_username" autofocus>

   <label for="id_email" class="sr-only">メールアドレス</label>
   <input type="email" name="email" placeholder="メールアドレス" maxlength="254" class="form-control mb-3" required id="id_email">

   <label for="id_password1" class="sr-only">パスワード</label>
   <input type="password" name="password1" placeholder="パスワード" autocomplete="new-password" class="form-control mb-3" id="id_password1">

   <label for="id_password2" class="sr-only">パスワード(確認用)</label>
   <input type="password" name="password2" placeholder="パスワード(確認用)" autocomplete="new-password" class="form-control mb-3" required id="id_password2">

   <button type="submit" class="btn btn-block btn-outline-success">Signup</button>
 </form>
  <p>既にアカウントをお持ちですか?? <a href="{% url 'user_app:login' %}">Login</a></p>
</div>
</div>
{% endblock %}